version: 0.0
os: linux
files:
  - source: /
    destination: /home/webapp/quiz-maker

permissions:
  - object: /home/webapp/quiz-maker
    owner: webapp
    group: webapp

hooks:
  AfterInstall:
    - location: ./scripts/after_install.sh
      timeout: 60
      runas: webapp
  ValidateService:
    - location: ./scripts/codedeploy-restart.sh
      runas: root