version: 2.1
executors:
  php745:
    docker:
      - image: circleci/php:7.4.5-node-browsers
commands:
  restore_composer_dev:
    steps:
      - restore_cache:
          name: Restore composer development
          key: composer-v1-{{ checksum "composer.lock" }}
  save_composer_dev:
    steps:
      - save_cache:
          name: Save composer development
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
  restore_npm:
    steps:
      - restore_cache:
          name: Restore npm install
          key: npm-v1-{{ checksum "package-lock.json" }}
  save_npm:
    steps:
      - save_cache:
          name: Save npm install
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  restore_composer_no_dev:
    steps:
      - restore_cache:
          name: Restore composer production
          key: composer-no-dev-v1-{{ checksum "composer.lock" }}
  save_composer_no_dev:
    steps:
      - save_cache:
          name: Save composer production
          key: composer-no-dev-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
jobs:
  build:
    executor:
      name: php745
    steps:
      - checkout
      - run: sudo composer self-update --1
      - restore_composer_dev
      - run: composer install -n --prefer-dist
      - save_composer_dev
      - restore_npm
      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - run: npm run prod
      - save_npm
      - run:
          name: php test
          command: vendor/bin/phpunit
  
  deploy:
    executor:
      name: php745
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
    steps:
      - checkout
      - run: sudo composer self-update --1
      - restore_composer_no_dev
      - run: composer install -n --no-dev --prefer-dist
      - save_composer_no_dev
      - restore_npm
      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - run: npm run prod
      - save_npm
      - run:
          name: archive artifacts
          command: zip -ryq quiz-maker.zip .