version: 2.1
executors:
  php745:
    docker:
      - image: circleci/php:7.4.5-node-browsers

commands:
  restore_composer_dev:
    steps:
      - restore_cache:
          name: Restore composer development
          key: composer-v1-{{ checksum "composer.lock" }}
  save_composer_dev:
    steps:
      - save_cache:
          name: Save composer development
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
  restore_composer_no_dev:
    steps:
      - restore_cache:
          name: Restore composer production
          key: composer-no-dev-v1-{{ checksum "composer.lock" }}
  save_composer_no_dev:
    steps:
      - save_cache:
          name: Save composer production
          key: composer-no-dev-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
  restore_npm:
    steps:
      - restore_cache:
          name: Restore npm install
          key: npm-v1-{{ checksum "package-lock.json" }}
  save_npm:
    steps:
      - save_cache:
          name: Save npm install
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  restore_webpack_cache_always:
    steps:
      - restore_cache:
          name: Resotere webpack cache
          key: weppack-v1
  save_webpack_cache_always:
    steps:
      - save_cache:
          name: Save webpack cache
          key: weppack-v1
          paths:
            - node_modules/.cache/webpack

jobs:
  build:
    executor:
      name: php745
    steps:
      - checkout
      - run: sudo composer self-update --1
      - restore_composer_dev
      - run: composer install -n --prefer-dist
      - save_composer_dev
      - restore_npm
      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_npm
      - restore_webpack_cache_always
      - run: npm run dev
      - save_webpack_cache_always
      - run:
          name: php test
          command: vendor/bin/phpunit
  
  deploy:
    executor:
      name: php745
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
    steps:
      - checkout
      - run: sudo composer self-update --1
      - restore_composer_no_dev
      - run: composer install -n --no-dev --prefer-dist
      - save_composer_no_dev
      - restore_npm
      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_npm
      - restore_webpack_cache_always
      - run: npm run prod
      - save_webpack_cache_always
      - run:
          name: archive artifacts
          command: zip -ryq quiz-maker.zip .
      - aws-cli/install
      - run:
          name: upload artifacts to s3
          command: aws s3 cp quiz-maker.zip s3://${AWS_S3_BUCKET_NAME}
      - run:
          name: deploy to prod
          command: |
            aws deploy create-deployment \
            --application-name quiz-maker \
            --deployment-group-name quiz-maker \
            --s3-location bucket=${AWS_S3_BUCKET_NAME},key=quiz-maker.zip,bundleType=zip

orbs:
  aws-cli: circleci/aws-cli@1.0.0

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master